name: flutter_youtube_downloader
description: YAYDIF

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^0.0.16
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.1.0
  cupertino_icons: ^0.1.3
  animated_layout: ^0.0.2
  cached_network_image: ^2.1.0+1
  hive: ^1.4.1+1
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 4ee135c
  path_provider: ^1.6.7
  html_unescape: ^1.0.1+3
  dio: ^3.0.9
  conditional_wrapper: ^1.0.1
  loading_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.2


flutter:
  uses-material-design: true
